development:
  adapter: postgresql
  encoding: unicode
  database: calculator_dev

test:
  adapter: postgresql
  encoding: unicode
  database: calculator_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
